import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState, useEffect } from 'react';
import { Box, Heading, Text, VStack, HStack, Link, Button, Divider, Image, useColorModeValue, Flex, IconButton, Drawer, DrawerBody, DrawerHeader, DrawerOverlay, DrawerContent, DrawerCloseButton, useDisclosure } from '@chakra-ui/react';
import { HamburgerIcon } from '@chakra-ui/icons';
import { FaGithub, FaLinkedin } from 'react-icons/fa';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sections = [
  { id: "home", label: "Home" },
  { id: "about", label: "About" },
  { id: "skills", label: "Skills" },
  { id: "projects", label: "Projects" },
  { id: "experience", label: "Experience" },
  { id: "contact", label: "Contact" },
];

function scrollToSection(id) {
  if (typeof window !== "undefined") {
    const el = document.getElementById(id);
    if (el) el.scrollIntoView({ behavior: "smooth" });
  }
}

export default function Home() {
  const { isOpen, onOpen, onClose } = useDisclosure();
  const [currentTitleIndex, setCurrentTitleIndex] = useState(0);
  
  const titles = [
    "Web Developer",
    "Mobile Developer", 
    "UI/UX Enthusiast"
  ];

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentTitleIndex((prev) => (prev + 1) % titles.length);
    }, 2000); // Change every 2 seconds

    return () => clearInterval(interval);
  }, [titles.length]);
  
  // Updated dark theme colors
  const navBg = useColorModeValue("white", "#121212");
  const navBorderColor = useColorModeValue("gray.200", "#3d3d3d");
  const buttonColor = useColorModeValue("gray.800", "white");
  const buttonHoverBg = useColorModeValue("gray.100", "#3d3d3d");
  const homeBg = useColorModeValue("gray.50", "#121212");
  const headingColor = useColorModeValue("gray.800", "white");
  const textColor = useColorModeValue("gray.600", "white");
  const sectionBg1 = useColorModeValue("white", "#121212");
  const sectionBg2 = useColorModeValue("gray.50", "#3d3d3d");
  const dividerColor = useColorModeValue("gray.200", "#3d3d3d");

  return (
    <>
      <Head>
        <title>Kyle Fernandez</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* Desktop Navigation */}
      <Flex 
        as="nav" 
        position="fixed" 
        top={0} 
        w="100%" 
        bg={navBg} 
        zIndex={10} 
        boxShadow="sm" 
        py={2}
        borderBottom="1px solid"
        borderColor={navBorderColor}
        justify="center"
        align="center"
        display={{ base: "none", lg: "flex" }}
      >
        <HStack justify="space-between" align="center" maxW="container.xl" w="100%" px={6}>
          <HStack>
            <Image 
              src="/assets/MyLogo.png" 
              alt="Logo" 
              height="50px" 
              width="auto" 
              objectFit="contain" 
            />
          </HStack>
          <HStack spacing={6}>
            {sections.map((section) => (
              <Button
                key={section.id}
                variant="ghost"
                onClick={() => scrollToSection(section.id)}
                color={buttonColor}
                _hover={{
                  bg: buttonHoverBg
                }}
              >
                {section.label}
              </Button>
            ))}
          </HStack>
        </HStack>
      </Flex>

      {/* Mobile Navigation */}
      <Flex 
        as="nav" 
        position="fixed" 
        top={0} 
        w="100%" 
        bg={navBg} 
        zIndex={10} 
        boxShadow="sm" 
        py={2}
        borderBottom="1px solid"
        borderColor={navBorderColor}
        justify="space-between"
        align="center"
        px={4}
        display={{ base: "flex", lg: "none" }}
      >
        <Image 
          src="/assets/MyLogo.png" 
          alt="Logo" 
          height="40px" 
          width="auto" 
          objectFit="contain" 
        />
        <IconButton
          aria-label="Open menu"
          icon={<HamburgerIcon />}
          variant="ghost"
          onClick={onOpen}
          color={buttonColor}
        />
      </Flex>

      {/* Mobile Drawer */}
      <Drawer isOpen={isOpen} placement="right" onClose={onClose}>
        <DrawerOverlay />
        <DrawerContent bg={navBg}>
          <DrawerCloseButton color={buttonColor} />
          <DrawerHeader color={headingColor}>Menu</DrawerHeader>
          <DrawerBody>
            <VStack spacing={4} align="stretch">
              {sections.map((section) => (
                <Button
                  key={section.id}
                  variant="ghost"
                  onClick={() => {
                    scrollToSection(section.id);
                    onClose();
                  }}
                  color={buttonColor}
                  _hover={{
                    bg: buttonHoverBg
                  }}
                  justifyContent="flex-start"
                  size="lg"
                >
                  {section.label}
                </Button>
              ))}
            </VStack>
          </DrawerBody>
        </DrawerContent>
      </Drawer>

      {/* Remove the pt={20} and adjust the home section */}
      <Box>
        {/* Home Section */}
        <Flex 
          id="home" 
          minH="100vh" 
          bg={homeBg}
          align="center"
          justify="center"
          px={{ base: 2, md: 6 }}
          pt={{ base: 16, md: 20 }} // Add top padding to account for fixed nav
        >
          <Flex 
            maxW="container.xl" 
            w="100%" 
            direction={{ base: "column-reverse", md: "column-reverse", lg: "row" }}
            align="center"
            justify="space-between"
            gap={{ base: 8, md: 12 }}
          >
            {/* Left Column - Introduction */}
            <Flex 
              direction="column" 
              flex={1}
              maxW={{ base: "100%", lg: "600px" }}
              mb={{ base: 8, md: 8, lg: 0 }}
            >
              <VStack align="start" spacing={4}>
                <Text 
                  color={textColor} 
                  fontSize={{ base: "md", md: "lg" }}
                  fontWeight="medium"
                  textTransform="uppercase"
                  letterSpacing="wide"
                >
                  Hello, I&apos;m
                </Text>
                
                <Heading 
                  size="2xl" 
                  color={headingColor}
                  lineHeight="1.1"
                  fontWeight="bold"
                  fontSize={{ base: "5xl", md: "6xl", lg: "7xl" }}
                >
                  Kyle Fernandez
                </Heading>
                
                <Heading 
                  size="xl" 
                  color="#458bd9"
                  fontWeight="semibold"
                  fontSize={{ base: "lg", md: "xl", lg: "2xl" }}
                  transition="opacity 1s ease-in-out"
                  opacity={1}
                  key={currentTitleIndex}
                  _before={{
                    content: `"${titles[currentTitleIndex]}"`,
                    position: "absolute",
                    opacity: 0,
                    transition: "opacity 1s ease-in-out"
                  }}
                >
                  {titles[currentTitleIndex]}
                </Heading>
                
                <Text 
                  fontSize={{ base: "md", md: "lg" }}
                  color={textColor}
                  lineHeight="1.7"
                  maxW="500px"
                >
                  I build exceptional digital experiences that combine beautiful design with powerful functionality. 
                  Passionate about creating web applications that make a difference.
                </Text>
                
                {/* <HStack spacing={4} pt={4} flexWrap="wrap">
                  <Button 
                    size="md" 
                    colorScheme="blue" 
                    bg={buttonHoverBg}
                    color="white"
                    _hover={{ bg: "#444444" }}
                    px={6}
                  >
                    View My Work
                  </Button>
                  <Button 
                    size="md" 
                    variant="outline" 
                    borderColor={buttonHoverBg}
                    color={buttonColor}
                    _hover={{ bg: buttonHoverBg, color: "white" }}
                    px={6}
                  >
                    Download CV
                  </Button>
                </HStack> */}
                <HStack spacing={4} pt={4} flexWrap="wrap">
                  {/* GitHub */}
                  <Button
                    as={Link}
                    href="https://github.com/SSimbah" // replace with your GitHub URL
                    target="_blank"
                    size="md"
                    variant="ghost"
                    leftIcon={<FaGithub size="20px" />}
                    color={buttonColor}
                    _hover={{ bg: buttonHoverBg }}
                    px={4}
                  >
                    GitHub
                  </Button>

                  {/* LinkedIn */}
                  <Button
                    as={Link}
                    href="https://linkedin.com/in/fernandez-kyle-owie-693802248/" // replace with your LinkedIn URL
                    target="_blank"
                    size="md"
                    variant="ghost"
                    leftIcon={<FaLinkedin size="20px" />}
                    color={buttonColor}
                    _hover={{ bg: buttonHoverBg }}
                    px={4}
                  >
                    LinkedIn
                  </Button>

                  {/* Download CV */}
                  <Button
                    as={Link}
                    href="/assets/Resume-KyleOwieFernandez.pdf" // update to actual file path
                    download
                    size="md"
                    variant="outline"
                    borderColor={buttonHoverBg}
                    color={buttonColor}
                    _hover={{ bg: buttonHoverBg, color: "white" }}
                    px={6}
                  >
                    Download CV
                  </Button>
                </HStack>
              </VStack>
            </Flex>
            
            {/* Right Column - Visual Element */}
            <Flex 
              flex={1}
              justify="center"
              align="center"
              maxW={{ base: "100%", lg: "500px" }}
            >
              <Box
                position="relative"
                w={{ base: "220px", sm: "350px", md: "400px", lg: "500px" }}
                h={{ base: "220px", sm: "350px", md: "400px", lg: "500px" }}
                borderRadius="full"
                // bg={buttonHoverBg}
                display="flex"
                align="center"
                justify="center"
                boxShadow="2xl"
              >
                <Image 
                  src="/assets/MyPicture.png" 
                  alt="Kyle Fernandez" 
                  borderRadius="full"
                  objectFit="cover"
                  w="100%"
                  h="100%"
                />
              </Box>
            </Flex>
          </Flex>
        </Flex>
        <Divider borderColor={dividerColor} />
        {/* About Section */}
        <Box 
          id="about" 
          minH="60vh" 
          py={20} 
          bg={sectionBg1}
        >
          <VStack spacing={4}>
            <Heading color={headingColor}>About Me</Heading>
            <Text 
              maxW="600px" 
              textAlign="center"
              color={textColor}
            >
              I am a passionate developer with experience in building web applications using modern technologies.
            </Text>
          </VStack>
        </Box>
        <Divider borderColor={dividerColor} />
        {/* Skills Section */}
        <Box 
          id="skills" 
          minH="60vh" 
          py={20} 
          bg={sectionBg2}
        >
          <VStack spacing={4}>
            <Heading color={headingColor}>Skills</Heading>
            <Text color={textColor}>
              JavaScript, React, Next.js, Chakra UI, Node.js, ...
            </Text>
          </VStack>
        </Box>
        <Divider borderColor={dividerColor} />
        {/* Projects Section */}
        <Box 
          id="projects" 
          minH="60vh" 
          py={20} 
          bg={sectionBg1}
        >
          <VStack spacing={4}>
            <Heading color={headingColor}>Projects</Heading>
            <Text color={textColor}>
              Project 1, Project 2, Project 3, ...
            </Text>
          </VStack>
        </Box>
        <Divider borderColor={dividerColor} />
        {/* Experience Section */}
        <Box 
          id="experience" 
          minH="60vh" 
          py={20} 
          bg={sectionBg2}
        >
          <VStack spacing={4}>
            <Heading color={headingColor}>Experience</Heading>
            <Text color={textColor}>
              Company 1, Company 2, ...
            </Text>
          </VStack>
        </Box>
        <Divider borderColor={dividerColor} />
        {/* Contact Section */}
        <Box 
          id="contact" 
          minH="60vh" 
          py={20} 
          bg={sectionBg1}
        >
          <VStack spacing={4}>
            <Heading color={headingColor}>Contact</Heading>
            <Text color={textColor}>
              Email: your.email@example.com
            </Text>
          </VStack>
        </Box>
      </Box>
    </>
  );
}
